avoid images

diff --git a/.github/workflows/lychee-link-checker.yml b/.github/workflows/lychee-link-checker.yml
--- a/.github/workflows/lychee-link-checker.yml
+++ b/.github/workflows/lychee-link-checker.yml
@@ -28,16 +28,14 @@ jobs:
 
       - name: Check markdown links for missing trailing slash
         run: |
-          echo "Checking markdown links for missing trailing slash..."
-
-          RESULTS=$(grep -Prn '\[[^]]+\]\((?!https?:\/\/)(?!.*#)([^)]+[^\/])\)' docs/**/*.md || true)
-
-          if [ -z "$RESULTS" ]; then
-            echo "✅ No missing trailing slashes found."
-            exit 0
-          else
-            echo "❌ Links missing trailing slashes found:"
-            echo "$RESULTS"
-            exit 1
-          fi          
+           echo "Checking markdown links for missing trailing slash in docs folder..."
+           RESULTS=$(grep -Prn '(?:(?<=^)|(?<=[^!]))\[[^\]]+\]\((\/[^)\s#]+)(?<!\/)\)' --include='*.md' docs/ || true)
+           if [ -z "$RESULTS" ]; then
+             echo "✅ No missing trailing slashes found."
+             exit 0
+           else
+             echo "❌ Links missing trailing slashes found:"
+             echo "$RESULTS"
+             exit 1
+           fi      
    
